'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, Check, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { cn } from '@/lib/utils'

const questions: Array<[string, string[]]> = [['What feels most worth improving?', ['My energy', 'My focus', 'My wellbeing', 'My routines']], ['How do you like to grow?', ['Tiny daily wins', 'A balanced mix', 'A serious challenge']], ['What does success feel like?', ['More consistent', 'More calm', 'More capable']]]
export default function Onboarding() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]); const [choice, setChoice] = useState(''); const [busy, setBusy] = useState(false); const router = useRouter(); const q = questions[step]
  async function next() { if (!choice) return; const nextAnswers = [...answers]; nextAnswers[step] = choice; if (step < questions.length - 1) { setAnswers(nextAnswers); setChoice(''); setStep(step + 1); return } setBusy(true); const response = await fetch('/api/onboarding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ answers: nextAnswers }) }); if (response.ok) router.push('/dashboard'); else setBusy(false) }
  return <main className="shell flex min-h-[calc(100vh-1rem)] items-center"><Card className="mx-auto w-full max-w-md overflow-hidden border-brand/20 shadow-xl shadow-brand/5"><CardContent className="p-5 sm:p-7"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-sm font-black text-brand"><Sparkles className="size-4" /> QUICK START</span><span className="text-sm font-bold text-muted-foreground">{step + 1}/{questions.length}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-brand transition-all" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><h1 className="mt-7 text-3xl font-black tracking-tight">{q[0]}</h1><p className="mt-2 text-sm text-muted-foreground">There is no wrong answer. We’ll shape your first routine around it.</p><div className="mt-7 grid gap-3">{q[1].map(option => <button type="button" key={option} onClick={() => setChoice(option)} className={cn('flex min-h-14 items-center gap-3 rounded-2xl border p-4 text-left font-bold transition', choice === option ? 'border-brand bg-brand/10 text-brand' : 'border-border hover:border-brand/50')}><span className={cn('grid size-6 place-items-center rounded-full border', choice === option ? 'border-brand bg-brand text-white' : 'border-border')}>{choice === option && <Check className="size-4" />}</span>{option}</button>)}</div><Button disabled={!choice || busy} onClick={() => void next()} size="lg" className="mt-7 w-full">{busy ? 'Setting up…' : step === questions.length - 1 ? 'Meet my habits' : 'Continue'}<ArrowRight className="ml-auto size-4" /></Button></CardContent></Card></main>
}
