import React from 'react';import {describe,it,expect,vi,afterEach} from 'vitest';import {render,screen,fireEvent,act,waitFor} from '@testing-library/react';import {TaskCard} from '@/components/TaskCard';import {ExpBar} from '@/components/ExpBar';import {Heatmap} from '@/components/Heatmap';import {StreakStats} from '@/components/StreakStats';import Onboarding from '@/app/onboarding/page';import Palettes from '@/app/palettes/page';

const push=vi.fn();
vi.mock('next/navigation',()=>({useRouter:()=>({push}),usePathname:()=>'/palettes'}));
vi.mock('@/components/Nav',()=>({Nav:()=>null}));

const json=(body:unknown,ok=true)=>Promise.resolve({ok,json:async()=>body});
afterEach(()=>{vi.restoreAllMocks();push.mockReset()});

describe('components',()=>{it('completes a task',async()=>{const fn=vi.fn();render(<TaskCard task={{id:'a',icon:'⚡',name:'Walk',category:'HEALTH',exp:20}} onComplete={fn}/>);await act(async()=>{fireEvent.click(screen.getByLabelText('Complete Walk'))});expect(fn).toHaveBeenCalledWith('a')});it('renders EXP and heatmap',()=>{render(<><ExpBar current={50} next={100}/><Heatmap values={[80]}/></>);expect(screen.getByLabelText('Experience 50 of 100')).toBeInTheDocument();expect(document.querySelectorAll('.heat')).toHaveLength(365)});it('shows current and personal-best streaks',()=>{render(<StreakStats currentStreak={4} longestStreak={12}/>);expect(screen.getByLabelText('Streak summary')).toHaveTextContent('4');expect(screen.getByLabelText('Streak summary')).toHaveTextContent('12')});it('shows palette lock states and only lets owned palettes be selected',async()=>{const fetchMock=vi.fn().mockResolvedValue(json({activePaletteId:'concrete',palettes:[{id:'concrete',name:'Concrete',rarity:'COMMON',colors:{primary:'43 43 43',accent:'255 90 54'},unlockLevel:1,requiresPrestige:false,owned:true,eligible:true},{id:'vault',name:'Vault',rarity:'LEGENDARY',colors:{primary:'43 43 43',accent:'47 109 181'},unlockLevel:8,requiresPrestige:false,owned:false,eligible:false}]}));vi.stubGlobal('fetch',fetchMock);render(<Palettes/>);const unlocked=await screen.findByRole('button',{name:/concrete/i});const locked=screen.getByRole('button',{name:/vault/i});expect(unlocked).toBeEnabled();expect(locked).toBeDisabled();expect(screen.getByText('Unlock at level 8')).toBeInTheDocument();fireEvent.click(unlocked);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/palettes',expect.objectContaining({method:'PATCH'})))});it('walks through onboarding and submits all three answers',async()=>{const fetchMock=vi.fn().mockResolvedValue(json({ok:true}));vi.stubGlobal('fetch',fetchMock);render(<Onboarding/>);fireEvent.click(screen.getByRole('button',{name:'Energy and movement'}));fireEvent.click(screen.getByRole('button',{name:/continue/i}));fireEvent.click(await screen.findByRole('button',{name:'Morning'}));fireEvent.click(screen.getByRole('button',{name:/continue/i}));fireEvent.click(await screen.findByRole('button',{name:'A little challenging'}));fireEvent.click(screen.getByRole('button',{name:/meet my habits/i}));await waitFor(()=>expect(push).toHaveBeenCalledWith('/dashboard'));expect(fetchMock).toHaveBeenCalledWith('/api/onboarding',expect.objectContaining({method:'POST',body:JSON.stringify({answers:['Energy and movement','Morning','A little challenging']})}))})});
