ALTER TABLE "User" ADD COLUMN "longestStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastVaultAppliedDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "lastPerfectWeekEnd" TIMESTAMP(3);
