import { NextResponse } from 'next/server';
import { z } from 'zod';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';

const addInput=z.object({taskId:z.string().min(1),iconOverride:z.string().max(12).optional(),personalTargetOverride:z.number().int().positive().optional(),unitOverride:z.enum(['REPS','MINUTES','KM','PAGES','CUSTOM']).optional()});
const manageInput=z.object({userTaskId:z.string().min(1),action:z.enum(['pause','resume','remove'])});
export async function GET(){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const [tasks,owned,stacks]=await Promise.all([prisma.task.findMany({orderBy:[{category:'asc'},{name:'asc'}]}),prisma.userTask.findMany({where:{userId:user.id},select:{taskId:true,isPaused:true}}),prisma.habitStack.findMany({include:{tasks:{include:{task:true}}}})]);return NextResponse.json({tasks,owned,stacks});}
export async function POST(request:Request){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});try{const data=addInput.parse(await request.json());await prisma.userTask.upsert({where:{userId_taskId:{userId:user.id,taskId:data.taskId}},update:{isPaused:false,iconOverride:data.iconOverride,personalTargetOverride:data.personalTargetOverride,unitOverride:data.unitOverride},create:{userId:user.id,...data}});return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'Please choose a valid habit and target.'},{status:400});}}
export async function PATCH(request:Request){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});try{const {userTaskId,action}=manageInput.parse(await request.json());const habit=await prisma.userTask.findFirst({where:{id:userTaskId,userId:user.id},select:{id:true}});if(!habit)return NextResponse.json({error:'Habit not found.'},{status:404});if(action==='remove'){await prisma.userTask.delete({where:{id:habit.id}});return NextResponse.json({ok:true,removed:true});}await prisma.userTask.update({where:{id:habit.id},data:{isPaused:action==='pause'}});return NextResponse.json({ok:true,paused:action==='pause'});}catch{return NextResponse.json({error:'Could not update this habit.'},{status:400});}}
