import { NextResponse } from 'next/server';
import { z } from 'zod';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';

const addInput=z.object({taskId:z.string().min(1),iconOverride:z.string().max(12).optional(),personalTargetOverride:z.number().int().positive().optional(),unitOverride:z.enum(['REPS','MINUTES','KM','PAGES','CUSTOM']).optional(),scheduleDays:z.array(z.number().int().min(0).max(6)).min(1).max(7).optional()});
const manageInput=z.object({userTaskId:z.string().min(1),action:z.enum(['pause','resume','remove','archive','restore','reorder']),sortOrder:z.number().int().optional()});
export async function GET(){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const [tasks,owned,stacks]=await Promise.all([prisma.task.findMany({orderBy:[{category:'asc'},{name:'asc'}]}),prisma.userTask.findMany({where:{userId:user.id},select:{id:true,taskId:true,isPaused:true,isArchived:true,archivedAt:true,scheduleDays:true,sortOrder:true,iconOverride:true,personalTargetOverride:true,unitOverride:true},orderBy:{sortOrder:'asc'}}),prisma.habitStack.findMany({include:{tasks:{include:{task:true}}}})]);return NextResponse.json({tasks,owned,stacks});}
export async function POST(request:Request){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});try{const data=addInput.parse(await request.json());await prisma.userTask.upsert({where:{userId_taskId:{userId:user.id,taskId:data.taskId}},update:{isPaused:false,isArchived:false,archivedAt:null,iconOverride:data.iconOverride,personalTargetOverride:data.personalTargetOverride,unitOverride:data.unitOverride,scheduleDays:data.scheduleDays??[0,1,2,3,4,5,6]},create:{userId:user.id,...data,scheduleDays:data.scheduleDays??[0,1,2,3,4,5,6],sortOrder:Date.now()}});return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'Please choose a valid habit and target.'},{status:400});}}
export async function PATCH(request:Request){const user=await currentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});try{const {userTaskId,action,sortOrder}=manageInput.parse(await request.json());const habit=await prisma.userTask.findFirst({where:{id:userTaskId,userId:user.id},select:{id:true}});if(!habit)return NextResponse.json({error:'Habit not found.'},{status:404});if(action==='remove'||action==='archive'){await prisma.userTask.update({where:{id:habit.id},data:{isArchived:true,archivedAt:new Date()}});return NextResponse.json({ok:true,archived:true});}if(action==='restore'){await prisma.userTask.update({where:{id:habit.id},data:{isArchived:false,archivedAt:null,isPaused:false}});return NextResponse.json({ok:true,restored:true});}if(action==='reorder'&&sortOrder!==undefined){await prisma.userTask.update({where:{id:habit.id},data:{sortOrder}});return NextResponse.json({ok:true,sortOrder});}await prisma.userTask.update({where:{id:habit.id},data:{isPaused:action==='pause'}});return NextResponse.json({ok:true,paused:action==='pause'});}catch{return NextResponse.json({error:'Could not update this habit.'},{status:400});}}
