import { Category, Difficulty, PrismaClient, Rarity, TaskType, Unit } from '@prisma/client'
const prisma = new PrismaClient()
type SeedTask=[string,string,string,Category,TaskType,number,number|null,number|null,Unit|null,Difficulty,boolean]
const tasks:SeedTask[]=[
['Push-ups','Build practical upper-body strength.','💪',Category.HEALTH,TaskType.PROGRESSIVE,20,10,1,Unit.REPS,Difficulty.MEDIUM,true],['Walk / light cardio','Movement clears the mind and supports your heart.','🚶',Category.HEALTH,TaskType.PROGRESSIVE,25,15,2,Unit.MINUTES,Difficulty.EASY,true],['Meditate','A small pause can reset your whole day.','🧘',Category.MENTAL,TaskType.STATIC,20,null,null,null,Difficulty.EASY,true],['Read a book','Reading grows your attention and perspective.','📚',Category.MENTAL,TaskType.PROGRESSIVE,20,10,1,Unit.PAGES,Difficulty.MEDIUM,true],['Wash face / skincare','A simple ritual is care you can feel.','✨',Category.SELF_CARE,TaskType.STATIC,15,null,null,null,Difficulty.EASY,true],['Bath / shower on schedule','Freshness is a quiet confidence boost.','🚿',Category.SELF_CARE,TaskType.STATIC,15,null,null,null,Difficulty.EASY,true],['Eat a healthy meal','Nourishment gives tomorrow’s self more energy.','🥗',Category.NUTRITION,TaskType.STATIC,20,null,null,null,Difficulty.EASY,true],['Drink 8 glasses of water','Hydration makes ordinary days work better.','💧',Category.NUTRITION,TaskType.PROGRESSIVE,15,8,.2,Unit.CUSTOM,Difficulty.EASY,true],
['Make your bed','Finish one promise before the day gets busy.','🛏️',Category.SELF_CARE,TaskType.STATIC,12,null,null,null,Difficulty.EASY,false],['Journal','Writing down thoughts makes them easier to carry.','📝',Category.MENTAL,TaskType.PROGRESSIVE,18,1,.1,Unit.PAGES,Difficulty.MEDIUM,false],['Stretch','Gentle mobility keeps your body ready for life.','🤸',Category.HEALTH,TaskType.PROGRESSIVE,15,5,1,Unit.MINUTES,Difficulty.EASY,false],['Cook a nourishing meal','Cooking lets you care for future you.','🍲',Category.NUTRITION,TaskType.STATIC,25,null,null,null,Difficulty.MEDIUM,false],['Morning sunlight','A few minutes of daylight can steady your sleep rhythm.','☀️',Category.HEALTH,TaskType.PROGRESSIVE,15,10,1,Unit.MINUTES,Difficulty.EASY,false],['Strength session','Strength work builds confidence that carries into daily life.','🏋️',Category.HEALTH,TaskType.PROGRESSIVE,35,20,2,Unit.MINUTES,Difficulty.HARD,false],['Breathing practice','Slow breathing gives your nervous system a reset.','🌬️',Category.MENTAL,TaskType.PROGRESSIVE,15,5,1,Unit.MINUTES,Difficulty.EASY,false],['Learn a skill','Deliberate practice turns curiosity into capability.','🎯',Category.MENTAL,TaskType.PROGRESSIVE,25,20,2,Unit.MINUTES,Difficulty.MEDIUM,false],['Tidy one space','A clear corner makes starting the next thing easier.','🧺',Category.SELF_CARE,TaskType.STATIC,15,null,null,null,Difficulty.EASY,false],['Plan tomorrow','A brief plan gives tomorrow a softer landing.','📅',Category.SELF_CARE,TaskType.STATIC,18,null,null,null,Difficulty.MEDIUM,false],['Prepare vegetables','Prep makes the nourishing choice easier later.','🥕',Category.NUTRITION,TaskType.STATIC,18,null,null,null,Difficulty.EASY,false],['Protein-focused meal','Protein supports recovery and steady energy.','🍳',Category.NUTRITION,TaskType.STATIC,22,null,null,null,Difficulty.MEDIUM,false],['Walk outdoors','Fresh air makes movement feel more restorative.','🌳',Category.HEALTH,TaskType.PROGRESSIVE,20,20,2,Unit.MINUTES,Difficulty.EASY,false],['Digital sunset','A screen-free wind-down protects your rest.','🌙',Category.SELF_CARE,TaskType.PROGRESSIVE,20,20,2,Unit.MINUTES,Difficulty.MEDIUM,false]
]
const idFor=(name:string)=>name.toLowerCase().replace(/[^a-z]/g,'').slice(0,24)
async function main(){
 for(const [name,why,icon,category,type,baseExp,baseTarget,scalingFactor,unit,difficultyTag,isStarterTask] of tasks){const id=idFor(name);await prisma.task.upsert({where:{id},update:{name,description:why,whyThisHabit:why,icon,category,type,baseExp,baseTarget,scalingFactor,unit,difficultyTag,isStarterTask},create:{id,name,description:why,whyThisHabit:why,icon,category,type,baseExp,baseTarget,scalingFactor,unit,difficultyTag,isStarterTask}})}
 const palettes=[['Concrete','255 90 54',Rarity.COMMON,1,false],['Clay','198 83 58',Rarity.COMMON,2,false],['Cobalt','47 109 181',Rarity.COMMON,3,false],['Moss','77 124 80',Rarity.COMMON,4,false],['Plum','125 75 130',Rarity.COMMON,5,false],['Ochre','196 142 51',Rarity.RARE,6,false],['Brick','157 62 47',Rarity.RARE,7,false],['Slate','71 91 108',Rarity.RARE,8,false],['Terracotta','195 90 60',Rarity.RARE,9,false],['Olive','111 123 58',Rarity.LEGENDARY,10,false],['Rust','171 71 45',Rarity.LEGENDARY,11,false],['Charcoal','51 51 51',Rarity.LEGENDARY,12,true]] as const
 for(let i=0;i<palettes.length;i++){const [name,accent,rarity,unlockLevel,requiresPrestige]=palettes[i];const colors={primary:'43 43 43',secondary:accent,background:'245 243 238',accent,text:'26 26 26'};await prisma.palette.upsert({where:{order:i+1},update:{name,rarity,colors,isSeasonal:false,unlockLevel,requiresPrestige},create:{order:i+1,name,rarity,colors,unlockLevel,requiresPrestige}})}
 const seasonal=[['Winter Slate','74 112 143',new Date('2026-12-01'),new Date('2026-12-31')],['Spring Rose','173 92 110',new Date('2027-03-01'),new Date('2027-03-31')],['Autumn Ink','91 69 105',new Date('2026-10-20'),new Date('2026-11-05')]] as const
 for(let i=0;i<seasonal.length;i++){const [name,accent,seasonStart,seasonEnd]=seasonal[i];const colors={primary:'43 43 43',secondary:accent,background:'245 243 238',accent,text:'26 26 26'};await prisma.palette.upsert({where:{order:i+13},update:{name,rarity:Rarity.SEASONAL,colors,isSeasonal:true,seasonStart,seasonEnd,unlockLevel:null,requiresPrestige:i===2},create:{order:i+13,name,rarity:Rarity.SEASONAL,colors,isSeasonal:true,seasonStart,seasonEnd,unlockLevel:null,requiresPrestige:i===2}})}
 const stackDefinitions=[['morning-routine','Morning Routine','A calm start: bed, water, and movement.',['Make your bed','Drink 8 glasses of water','Stretch']],['evening-wind-down','Evening Wind-down','Close the day with care, reflection, and a softer landing.',['Wash face / skincare','Journal','Digital sunset']]] as const
 for(const [id,name,description,names] of stackDefinitions){
  await prisma.habitStack.upsert({where:{id},update:{name,description},create:{id,name,description}})
  for(const taskId of names.map(idFor)) await prisma.habitStackTask.upsert({where:{stackId_taskId:{stackId:id,taskId}},update:{},create:{stackId:id,taskId}})
 }
 for(const [key,name,description,icon] of [['streak7','Seven steady days','Showed up for seven days.','🔥'],['streak30','Thirty day rhythm','Built a month of momentum.','🌋'],['first_month','First month','Completed the first month.','🗓️'],['completions100','Century','Reached 100 total completions.','💯'],['perfect_week','Perfect week','Completed every active habit for a week.','💫'],['first_prestige','First prestige','Started a new chapter with prestige.','👑']] as const)await prisma.badge.upsert({where:{key},update:{name,description,icon},create:{key,name,description,icon}})
}
main().finally(()=>prisma.$disconnect())
