'use client'
import React from 'react'
import { useRef,useState } from 'react'
import { motion,useReducedMotion } from 'framer-motion'
import { ArrowRight,Check,Sparkles } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
export type Habit={id:string;icon:string;name:string;category:string;target?:string;exp:number;done?:boolean}
export function TaskCard({task,onComplete,index=0}:{task:Habit;onComplete:(id:string)=>Promise<void>|void;index?:number}){const start=useRef(0);const [busy,setBusy]=useState(false);const reduced=useReducedMotion();const complete=async()=>{if(busy||task.done)return;setBusy(true);await onComplete(task.id);setBusy(false)};return <motion.article initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={reduced?{duration:0}:{delay:index*.045,duration:.24}} className={cn('card group relative overflow-hidden p-4',task.done&&'opacity-65')} onPointerDown={e=>{start.current=e.clientX}} onPointerUp={e=>{if(e.clientX-start.current>75)void complete()}}><div className="flex items-start gap-3"><div className={cn('grid size-12 shrink-0 place-items-center border-2 border-border bg-accent text-2xl',task.done&&'bg-emerald-400')}><motion.span animate={task.done&&!reduced?{scale:[1,1.25,1],rotate:[0,-8,0]}:{}}>{task.done?<Check className="size-6"/>:task.icon}</motion.span></div><div className="min-w-0 flex-1"><Badge>{task.category.replace('_',' ')}</Badge><h3 className="mt-2 truncate font-black tracking-tight">{task.name}</h3><p className="mt-1 text-sm text-muted-foreground">{task.target??'Quick daily win'} <span className="mx-1">·</span><span className="font-black text-brand">{task.exp} EXP</span></p></div><motion.button whileTap={reduced?{}:{scale:.86,rotate:-8}} aria-label={`Complete ${task.name}`} disabled={busy||task.done} onClick={()=>void complete()} className={cn('grid size-11 shrink-0 place-items-center border-2 border-border bg-brand text-white shadow-[3px_3px_0_rgb(var(--shadow))] disabled:bg-emerald-400 disabled:text-foreground disabled:shadow-none')}><span className="sr-only">{task.done?'Completed':'Complete'}</span>{task.done?<Check className="size-5"/>:<ArrowRight className="size-5"/>}</motion.button></div><p className="mt-4 flex items-center gap-1.5 text-[11px] font-bold text-muted-foreground"><Sparkles className="size-3.5 text-accent"/>Swipe right or tap when it is honestly done.</p></motion.article>}
