'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ExpBar } from '@/components/ExpBar';
import { TaskCard,Habit } from '@/components/TaskCard';
import { Nav } from '@/components/Nav';

type Dashboard={user:{displayName:string;level:number;title:string;totalExp:number;nextExp:number};tasks:Habit[];done:number;growth:number|null;streak:number};
export default function Dashboard(){const [data,setData]=useState<Dashboard|null>(null);const [toast,setToast]=useState('');const load=async()=>{try{const response=await fetch('/api/dashboard');setData(response.ok?await response.json():null);}catch{setData(null)}};useEffect(()=>{void load()},[]);async function complete(id:string){const response=await fetch('/api/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userTaskId:id})});const result=await response.json();if(!response.ok){setToast(result.message??result.error??'Could not record this win.');return}setToast(`+${result.exp} EXP — nice work.`);void load();setTimeout(()=>setToast(''),2600)}if(!data)return <main className="shell"><div className="card animate-pulse p-5"><div className="h-7 w-48 rounded bg-brand/15"/><div className="mt-5 h-3 rounded bg-brand/10"/><div className="mt-5 grid grid-cols-2 gap-3"><div className="h-20 rounded bg-brand/10"/><div className="h-20 rounded bg-brand/10"/></div></div><Nav/></main>;return <main className="shell"><header className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-brand">TODAY’S QUEST</p><h1 className="text-2xl font-black">Hi, {data.user.displayName}</h1><p className="text-sm text-[rgb(var(--muted))]">Level {data.user.level} · {data.user.title}</p></div><div className="rounded-xl bg-accent/20 p-3 text-center"><b className="block text-lg">{data.done}/{data.tasks.length}</b><span className="text-xs">wins</span></div></div><div className="mt-5"><ExpBar current={data.user.totalExp} next={data.user.nextExp}/></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-brand/10 p-3"><span className="text-xs font-bold text-brand">STREAK</span><b className="block text-xl">{data.streak} day{data.streak===1?'':'s'} 🔥</b></div><div className="rounded-xl bg-accent/15 p-3"><span className="text-xs font-bold text-brand">TODAY’S GROWTH</span><b className="block text-xl">{data.growth===null?'Getting started':`${data.growth>0?'+':''}${data.growth}%`}</b></div></div></header><section className="mt-5"><div className="mb-3 flex justify-between"><h2 className="text-lg font-black">Today’s habits</h2><Link className="font-bold text-brand" href="/library">+ Add</Link></div>{data.tasks.length?<div className="task-grid grid gap-3">{data.tasks.map(task=><TaskCard key={task.id} task={task} onComplete={complete}/>)}</div>:<div className="card p-8 text-center"><div className="text-4xl">🌱</div><h2 className="mt-3 font-black">Make today yours</h2><p className="mt-1 text-sm text-[rgb(var(--muted))]">Pick a habit from the library to begin.</p><Link className="btn btn-primary mt-4" href="/library">Explore habits</Link></div>}</section>{toast&&<div role="status" className="fixed bottom-24 left-1/2 z-20 -translate-x-1/2 rounded-full bg-[rgb(var(--ink))] px-5 py-3 text-sm font-bold text-white shadow-xl">{toast}</div>}<Nav/></main>}
